# This is a basic workflow to help you get started with Actions

name: Azure CI

# Controls when the action will run. 
on:
  push:
    branches:
      - main
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Azure CLI - Show Status
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az account show

    - name: Azure CLI - Bicep Installation
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az bicep install
          az bicep --help

    - name: Azure CLI - Plan
      if: github.event_name == 'pull_request'
      uses: azure/CLI@v1
      with: 
        inlineScript: |
          az deployment sub what-if --location 'Switzerland North' -f $GITHUB_WORKSPACE/Templates/main.bicep -p location='switzerlandnorth'
