# This is a basic workflow to help you get started with Actions

name: Azure CI

# Controls when the action will run. 
on:
  push:
    branches:
      - main
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2

    - run: | 
          curl -Lo bicepinstall https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
          chmod +x ./bicepinstall
          sudo mv ./bicepinstall /usr/local/bin/bicep
          bicep --help

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Azure CLI - Show Status
      uses: azure/CLI@v1
      with:
        azcliversion: 2.20.0
        inlineScript: |
          az account show

    - name: Azure CLI - Plan
      if: github.event_name == 'pull_request'
      uses: azure/CLI@v1
      with: 
        azcliversion: 2.20.0
        inlineScript: |
          sh $GITHUB_WORKSPACE/plan.sh
